name: ofp105
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy

  # - gitpython
  # - rich
  - pyserial
  # - more-itertools
  - pyyaml

  - pip
  - pip:
    - dearpygui
    - dearpygui_ext
    - easygui

